name: 'Run tflint with reviewdog'
description: '🐶 Run tflint with reviewdog on pull requests to enforce best practices'
author: 'vlaaaaaaad (reviewdog)'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . ( root of the repository)
    default: '.'
  flags:
    description: |
      List of arguments to send to tflint
      For the output to be parsable by reviewdog --format=checkstyle is enforced
      Default is --module.
    default: '--module'

outputs:
  tflint-return-code:
    description: 'tflint command return code'
  reviewdog-return-code:
    description: 'reviewdog command return code'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'edit'
  color: 'gray-dark'
