name: depup

on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-depup/with-pr@v1
        with:
          file: action.yml
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog
          labels: "bump:minor"
