name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@master

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)
