name: Test module

on:
  pull_request:

jobs:
  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / tflint (github-pr-check)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - run: terraform init
        working-directory: testdata_module

      - uses: ./
        continue-on-error: true
        id: test
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: info
          working_directory: testdata_module
          tflint_version: v0.23.0

      # The check is expected to fail on the test data
      - name: Check return codes
        if: success() || failure ()
        run: |
          tflint_return="${{ steps.test.outputs.tflint-return-code }}"
          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
          if [ "$tflint_return" -eq 3 ]; then
            echo "tflint correctly returned failure ${tflint_return}"
          else
            echo "tflint returned ${tflint_return}, expected '3'. Failing..."
            exit 1
          fi
          if [ "$reviewdog_return" -eq 0 ]; then
            echo "reviewdog correctly returned success: ${reviewdog_return}"
          else
            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
            exit 1
          fi
